server {
    listen 80;
    server_name localhost;
    root /var/www/htmx_website;

    # Serve static files
    location /styles/ {
        alias /var/www/htmx_website/styles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /templates/ {
        alias /var/www/htmx_website/templates/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /logos/ {
        alias /var/www/htmx_website/logos/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Handle other dynamic requests
    location / {
        try_files $uri @flask;
    }

    # Proxy requests to Flask
    location @flask {
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Fix for large files
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }

    # Custom 404 error page
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/htmx_website;
    }
}
